services:
  softylines_sylius_testimonial.filesystem.store_logo:
    class: Gaufrette\Filesystem
    arguments:
      - 'store_logo'
    factory:
      - '@knp_gaufrette.filesystem_map'
      - 'get'

  softylines_sylius_testimonial.uploader.store_logo:
    class: Softylines\SyliusTestimonialPlugin\Uploader\AvatarUploader
    arguments:
      - '@softylines_sylius_testimonial.filesystem.store_logo'
