softylines_sylius_testimonial_admin_testimonial:
    resource: |
        alias: softylines_sylius_testimonial.testimonial
        section: admin
        templates: '@SyliusAdmin\\Crud'
        redirect: update
        grid: softylines_sylius_testimonial_admin_testimonial
        vars:
            all:
                subheader: softylines_sylius_testimonial.ui.manage_testimonials
            index:
                icon: 'comment'
    type: sylius.resource
