imports:
    - { resource: resources.yaml }
    - { resource: grids.yaml }

knp_gaufrette:
    adapters:
        avatar:
            local:
                directory: "%sylius_core.public_dir%/media/testimonial/avatar"
                create: true
    filesystems:
        avatar:
            adapter: avatar

liip_imagine:
    loaders:
        avatar:
            filesystem:
                data_root: "%kernel.project_dir%/public/media/testimonial/avatar"
    filter_sets:
        softylines_sylius_testimonial_plugin_avatar:
            data_loader: avatar
            filters:
                thumbnail: { size: [300, 300], mode: outbound }